
package lab4;

/**
 *
 * @author Esteban
 */
public class VentanaGitAdd extends javax.swing.JFrame {

    /**
     * Creates new form VentanaGitAdd
     */
    VentanaPrincipal interfaz;
    public VentanaGitAdd(VentanaPrincipal ventana) {
        this.interfaz = ventana;
        initComponents();
        
    }
    public VentanaGitAdd() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btGitAdd = new javax.swing.JButton();
        btGitAddAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaNombresArchivos = new javax.swing.JTextArea();
        jLabelIngresarNombresArchivos = new javax.swing.JLabel();
        jLabelGitAddAll = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btGitAdd.setText("Add");
        btGitAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGitAddActionPerformed(evt);
            }
        });
        getContentPane().add(btGitAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        btGitAddAll.setText("Add All");
        btGitAddAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGitAddAllActionPerformed(evt);
            }
        });
        getContentPane().add(btGitAddAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        jTextAreaNombresArchivos.setColumns(20);
        jTextAreaNombresArchivos.setRows(5);
        jScrollPane1.setViewportView(jTextAreaNombresArchivos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 300, 150));

        jLabelIngresarNombresArchivos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelIngresarNombresArchivos.setText("Ingrese los nombres de los archivos (separados por un salto de linea):");
        getContentPane().add(jLabelIngresarNombresArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabelGitAddAll.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelGitAddAll.setText("Presione aquí si desea hacer un GitAdd -All:");
        getContentPane().add(jLabelGitAddAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btGitAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGitAddActionPerformed
        this.interfaz.archivosAdd = this.jTextAreaNombresArchivos.getText();
        this.setVisible(false);
    }//GEN-LAST:event_btGitAddActionPerformed

    private void btGitAddAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGitAddAllActionPerformed
        this.interfaz.archivosAdd = "AddAll";
        this.setVisible(false);
    }//GEN-LAST:event_btGitAddAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGitAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGitAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGitAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGitAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaGitAdd().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGitAdd;
    private javax.swing.JButton btGitAddAll;
    private javax.swing.JLabel jLabelGitAddAll;
    private javax.swing.JLabel jLabelIngresarNombresArchivos;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextAreaNombresArchivos;
    // End of variables declaration//GEN-END:variables
}
