
package lab4;

import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Esteban
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    String nombreAutor;
    String nombreRepo;
    Repositorio repo;
    /**
     * Creates new form Ventana
     * @param autor
     * @param repo
     */
    public VentanaPrincipal(String autor, String repo) {
        this.nombreAutor = autor;
        this.nombreRepo = repo;
        this.repo = Repositorio.gitInit(autor, repo);
        initComponents();    
    }

    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textWorkspace = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textIndex = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textLocalRepository = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        textRemoteRepository = new javax.swing.JTextArea();
        jLabelWorkspace = new javax.swing.JLabel();
        jLabelIndex = new javax.swing.JLabel();
        jLabelLocalRepository = new javax.swing.JLabel();
        jLabelRemoteRepository = new javax.swing.JLabel();
        btGitAdd = new javax.swing.JButton();
        btGitPush = new javax.swing.JButton();
        btGitPull = new javax.swing.JButton();
        btGitCommit = new javax.swing.JButton();
        btCrearArchivo = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        btGitLog = new javax.swing.JButton();
        textFieldNombreArchivo = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAreaContenidoArchivo = new javax.swing.JTextArea();
        jLabelNombreArchivo = new javax.swing.JLabel();
        jLabelContenidoArchivo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textWorkspace.setColumns(20);
        textWorkspace.setRows(5);
        textWorkspace.setEditable(false);
        jScrollPane1.setViewportView(textWorkspace);

        textIndex.setColumns(20);
        textIndex.setRows(5);
        textIndex.setEditable(false);
        jScrollPane2.setViewportView(textIndex);

        textLocalRepository.setColumns(20);
        textLocalRepository.setRows(5);
        textLocalRepository.setEditable(false);
        jScrollPane3.setViewportView(textLocalRepository);

        textRemoteRepository.setColumns(20);
        textRemoteRepository.setRows(5);
        textRemoteRepository.setEditable(false);
        jScrollPane4.setViewportView(textRemoteRepository);

        jLabelWorkspace.setText("Workspace");

        jLabelIndex.setText("Index");

        jLabelLocalRepository.setText("Local Repository");

        jLabelRemoteRepository.setText("Remote Repository");

        btGitAdd.setText("Git Add");
        btGitAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGitAddActionPerformed(evt);
            }
        });

        btGitPush.setText("Git Push");

        btGitPull.setText("Git Pull");

        btGitCommit.setText("Git Commit");
        btGitCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGitCommitActionPerformed(evt);
            }
        });

        btCrearArchivo.setText("Agregar Archivo");
        btCrearArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearArchivoActionPerformed(evt);
            }
        });

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        btGitLog.setText("Git Log");

        textFieldNombreArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreArchivoActionPerformed(evt);
            }
        });

        textAreaContenidoArchivo.setColumns(20);
        textAreaContenidoArchivo.setRows(5);
        jScrollPane5.setViewportView(textAreaContenidoArchivo);

        jLabelNombreArchivo.setText("Nombre Archivo:");

        jLabelContenidoArchivo.setText("Contenido del Archivo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabelWorkspace)
                        .addGap(139, 139, 139)
                        .addComponent(jLabelIndex)
                        .addGap(157, 157, 157)
                        .addComponent(jLabelLocalRepository)
                        .addGap(110, 110, 110)
                        .addComponent(jLabelRemoteRepository))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btGitPull)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btGitAdd)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 627, Short.MAX_VALUE)
                                                .addComponent(jLabelNombreArchivo))
                                            .addComponent(btGitLog))
                                        .addGap(10, 10, 10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btGitPush)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabelContenidoArchivo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldNombreArchivo)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btGitCommit)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSalir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btCrearArchivo)
                                .addGap(29, 29, 29)))))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelWorkspace)
                    .addComponent(jLabelIndex)
                    .addComponent(jLabelLocalRepository)
                    .addComponent(jLabelRemoteRepository))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btGitAdd)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNombreArchivo))
                        .addGap(4, 4, 4)))
                .addComponent(btGitCommit)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btGitPush)
                        .addGap(18, 18, 18)
                        .addComponent(btGitPull)
                        .addGap(18, 18, 18)
                        .addComponent(btGitLog))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelContenidoArchivo)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalir)
                    .addComponent(btCrearArchivo))
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btGitAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGitAddActionPerformed
       
       /* ArrayList<String> contenido = new ArrayList<>();
        contenido.add("Hola ");
        contenido.add("como ");
        contenido.add("están? ");
        ArchivoDeTextoPlano arch = new ArchivoDeTextoPlano("Archivo1.txt",contenido);
        this.textWorkspace.setText(arch.nombreArchivo + "\n" + arch.fecha + "\n" + arch.texto.get(0) + arch.texto.get(1) + arch.texto.get(2) + this.nombreAutor + this.nombreRepo);*/
    }//GEN-LAST:event_btGitAddActionPerformed

    private void btGitCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGitCommitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btGitCommitActionPerformed

    private void btCrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearArchivoActionPerformed
        ArrayList<String> contenido = new ArrayList<>();
        String contenidoEnString = this.textAreaContenidoArchivo.getText();
        String[] contenidoEnStringSeparado = contenidoEnString.split("\n");
        contenido.addAll(Arrays.asList(contenidoEnStringSeparado));         
        ArchivoDeTextoPlano archivo = new ArchivoDeTextoPlano(this.textFieldNombreArchivo.getText(),contenido);
        String archivoAString = this.textWorkspace.getText() + "------------------------------------------------ \n" +archivo.toString();
        this.textWorkspace.setText(archivoAString);
    }//GEN-LAST:event_btCrearArchivoActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    private void textFieldNombreArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrearArchivo;
    private javax.swing.JButton btGitAdd;
    private javax.swing.JButton btGitCommit;
    private javax.swing.JButton btGitLog;
    private javax.swing.JButton btGitPull;
    private javax.swing.JButton btGitPush;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabelContenidoArchivo;
    private javax.swing.JLabel jLabelIndex;
    private javax.swing.JLabel jLabelLocalRepository;
    private javax.swing.JLabel jLabelNombreArchivo;
    private javax.swing.JLabel jLabelRemoteRepository;
    private javax.swing.JLabel jLabelWorkspace;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea textAreaContenidoArchivo;
    private javax.swing.JTextField textFieldNombreArchivo;
    private javax.swing.JTextArea textIndex;
    private javax.swing.JTextArea textLocalRepository;
    private javax.swing.JTextArea textRemoteRepository;
    private javax.swing.JTextArea textWorkspace;
    // End of variables declaration//GEN-END:variables
}
