
package lab4;

import javax.swing.JOptionPane;

/**
 *
 * @author Esteban
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    String nombreAutor;
    String nombreRepo;
    String archivosAdd;
    Repositorio repo;
    /**
     * Creates new form Ventana
     * @param autor
     * @param repo
     */
    public VentanaPrincipal(String autor, String repo) {
        this.nombreAutor = autor;
        this.nombreRepo = repo;
        this.repo = Repositorio.gitInit(autor, repo);        
        initComponents();    
        this.jTextAreaNombreAutorYRepo.setText("El nombre del Autor es: "+this.nombreAutor+"\nEl nombre del Repositorio es: "+this.nombreRepo);
    }

    public VentanaPrincipal() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textWorkspace = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textIndex = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textLocalRepository = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        textRemoteRepository = new javax.swing.JTextArea();
        jLabelWorkspace = new javax.swing.JLabel();
        jLabelIndex = new javax.swing.JLabel();
        jLabelLocalRepository = new javax.swing.JLabel();
        jLabelRemoteRepository = new javax.swing.JLabel();
        btGitAdd = new javax.swing.JButton();
        btGitPush = new javax.swing.JButton();
        btGitPull = new javax.swing.JButton();
        btGitCommit = new javax.swing.JButton();
        btCrearArchivo = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();
        btGitLog = new javax.swing.JButton();
        textFieldNombreArchivo = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAreaContenidoArchivo = new javax.swing.JTextArea();
        jLabelNombreArchivo = new javax.swing.JLabel();
        jLabelContenidoArchivo = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaNombreAutorYRepo = new javax.swing.JTextArea();
        jLabelDatosRepo = new javax.swing.JLabel();
        jButtonActualizarIndex = new javax.swing.JButton();
        jButtonActualizarLocal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textWorkspace.setColumns(20);
        textWorkspace.setRows(5);
        textWorkspace.setEditable(false);
        jScrollPane1.setViewportView(textWorkspace);

        textIndex.setColumns(20);
        textIndex.setRows(5);
        textIndex.setEditable(false);
        jScrollPane2.setViewportView(textIndex);

        textLocalRepository.setColumns(20);
        textLocalRepository.setRows(5);
        textLocalRepository.setEditable(false);
        jScrollPane3.setViewportView(textLocalRepository);

        textRemoteRepository.setColumns(20);
        textRemoteRepository.setRows(5);
        textRemoteRepository.setEditable(false);
        jScrollPane4.setViewportView(textRemoteRepository);

        jLabelWorkspace.setText("Workspace");

        jLabelIndex.setText("Index");

        jLabelLocalRepository.setText("Local Repository");

        jLabelRemoteRepository.setText("Remote Repository");

        btGitAdd.setText("Git Add");
        btGitAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGitAddActionPerformed(evt);
            }
        });

        btGitPush.setText("Git Push");

        btGitPull.setText("Git Pull");

        btGitCommit.setText("Git Commit");
        btGitCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGitCommitActionPerformed(evt);
            }
        });

        btCrearArchivo.setText("Agregar Archivo");
        btCrearArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearArchivoActionPerformed(evt);
            }
        });

        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        btGitLog.setBackground(new java.awt.Color(51, 255, 255));
        btGitLog.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btGitLog.setForeground(new java.awt.Color(255, 0, 255));
        btGitLog.setText("Git Log");

        textFieldNombreArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNombreArchivoActionPerformed(evt);
            }
        });

        textAreaContenidoArchivo.setColumns(20);
        textAreaContenidoArchivo.setRows(5);
        jScrollPane5.setViewportView(textAreaContenidoArchivo);

        jLabelNombreArchivo.setText("Nombre Archivo:");

        jLabelContenidoArchivo.setText("Contenido del Archivo:");

        jTextAreaNombreAutorYRepo.setColumns(20);
        jTextAreaNombreAutorYRepo.setRows(5);
        jTextAreaNombreAutorYRepo.setEditable(false);
        jScrollPane6.setViewportView(jTextAreaNombreAutorYRepo);

        jLabelDatosRepo.setText("Datos Del Repositorio");

        jButtonActualizarIndex.setText("ACTUALIZAR INDEX");
        jButtonActualizarIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarIndexActionPerformed(evt);
            }
        });

        jButtonActualizarLocal.setText("ACTUALIZAR LOCAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabelWorkspace)
                .addGap(139, 139, 139)
                .addComponent(jLabelIndex)
                .addGap(154, 154, 154)
                .addComponent(jLabelLocalRepository)
                .addGap(113, 113, 113)
                .addComponent(jLabelRemoteRepository)
                .addGap(189, 189, 189)
                .addComponent(jLabelDatosRepo))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jButtonActualizarIndex)
                .addGap(71, 71, 71)
                .addComponent(jButtonActualizarLocal)
                .addGap(279, 279, 279)
                .addComponent(jLabelNombreArchivo)
                .addGap(40, 40, 40)
                .addComponent(textFieldNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(btGitAdd)
                .addGap(13, 13, 13)
                .addComponent(btGitCommit)
                .addGap(17, 17, 17)
                .addComponent(btGitPush)
                .addGap(19, 19, 19)
                .addComponent(btGitPull)
                .addGap(35, 35, 35)
                .addComponent(btGitLog)
                .addGap(219, 219, 219)
                .addComponent(jLabelContenidoArchivo)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btSalir)
                .addGap(982, 982, 982)
                .addComponent(btCrearArchivo))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWorkspace)
                    .addComponent(jLabelIndex)
                    .addComponent(jLabelLocalRepository)
                    .addComponent(jLabelRemoteRepository)
                    .addComponent(jLabelDatosRepo))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonActualizarIndex)
                    .addComponent(jButtonActualizarLocal)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabelNombreArchivo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(textFieldNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btGitAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btGitCommit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btGitPush))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btGitPull))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(btGitLog))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabelContenidoArchivo))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSalir)
                    .addComponent(btCrearArchivo)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btGitAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGitAddActionPerformed
       VentanaGitAdd ventanitaAdd = new VentanaGitAdd(this);
       ventanitaAdd.setVisible(true);
       /*debido que al abrir la ventanitaAdd los String ingresados en esta no se hacen presente de inmediato aca,
       es que el verdadero metodo GitAdd se ejecuta con el boton 'ACTUALIZAR INDEX'*/
    }//GEN-LAST:event_btGitAddActionPerformed

    private void btGitCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGitCommitActionPerformed
        System.out.println("Esto es Git Commit");        
    }//GEN-LAST:event_btGitCommitActionPerformed
    
    private void btCrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearArchivoActionPerformed
        if(this.textFieldNombreArchivo.getText().length() >= 1){
            this.repo.crearArchivo(this.textFieldNombreArchivo.getText(), this.textAreaContenidoArchivo.getText());
            String wsString = this.repo.workspace.toString();
            this.textWorkspace.setText(wsString);        
        }
        else{
            JOptionPane.showMessageDialog(null,"DEBE INGRESAR EL NOMBRE DEL ARCHIVO PARA AGREGARLO.","operación mal ingresada",JOptionPane.INFORMATION_MESSAGE);
        }
        this.textFieldNombreArchivo.setText("");
        this.textAreaContenidoArchivo.setText("");
    }//GEN-LAST:event_btCrearArchivoActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    private void textFieldNombreArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNombreArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNombreArchivoActionPerformed

    private void jButtonActualizarIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarIndexActionPerformed
        if("AddAll".equals(this.archivosAdd)){
            this.repo.gitAdd();
        }
        else{
            this.repo.gitAdd(this.archivosAdd);
        }
        this.textIndex.setText(this.repo.index.toString());
        this.archivosAdd = "";
    }//GEN-LAST:event_jButtonActualizarIndexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrearArchivo;
    private javax.swing.JButton btGitAdd;
    private javax.swing.JButton btGitCommit;
    private javax.swing.JButton btGitLog;
    private javax.swing.JButton btGitPull;
    private javax.swing.JButton btGitPush;
    private javax.swing.JButton btSalir;
    private javax.swing.JButton jButtonActualizarIndex;
    private javax.swing.JButton jButtonActualizarLocal;
    private javax.swing.JLabel jLabelContenidoArchivo;
    private javax.swing.JLabel jLabelDatosRepo;
    private javax.swing.JLabel jLabelIndex;
    private javax.swing.JLabel jLabelLocalRepository;
    private javax.swing.JLabel jLabelNombreArchivo;
    private javax.swing.JLabel jLabelRemoteRepository;
    private javax.swing.JLabel jLabelWorkspace;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextAreaNombreAutorYRepo;
    private javax.swing.JTextArea textAreaContenidoArchivo;
    private javax.swing.JTextField textFieldNombreArchivo;
    private javax.swing.JTextArea textIndex;
    private javax.swing.JTextArea textLocalRepository;
    private javax.swing.JTextArea textRemoteRepository;
    private javax.swing.JTextArea textWorkspace;
    // End of variables declaration//GEN-END:variables
}
