
package lab4;

import javax.swing.JOptionPane;

/**
 *
 * @author Esteban
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    String nombreAutor;
    String nombreRepo;
    Repositorio repo;
    /**
     * Creates new form Ventana
     * @param autor
     * @param repo
     */
    public VentanaPrincipal(String autor, String repo) {
        this.nombreAutor = autor;
        this.nombreRepo = repo;
        this.repo = Repositorio.gitInit(autor, repo);        
        initComponents();    
        this.jTextAreaNombreAutorYRepo.setText("El nombre del Autor es: "+this.nombreAutor+"\nEl nombre del Repositorio es: "+this.nombreRepo);
    }

    public VentanaPrincipal() {        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textWorkspace = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textIndex = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        textLocalRepository = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        textRemoteRepository = new javax.swing.JTextArea();
        jLabelWorkspace = new javax.swing.JLabel();
        jLabelIndex = new javax.swing.JLabel();
        jLabelLocalRepository = new javax.swing.JLabel();
        jLabelRemoteRepository = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextAreaNombreAutorYRepo = new javax.swing.JTextArea();
        jLabelDatosRepo = new javax.swing.JLabel();
        panel3 = new java.awt.Panel();
        textFieldNombreArchivo = new javax.swing.JTextField();
        jLabelNombreArchivo = new javax.swing.JLabel();
        jLabelContenidoArchivo = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        textAreaContenidoArchivo = new javax.swing.JTextArea();
        btCrearArchivo = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        btGitAdd = new javax.swing.JButton();
        btGitCommit = new javax.swing.JButton();
        btGitPush = new javax.swing.JButton();
        btGitPull = new javax.swing.JButton();
        btGitLog = new javax.swing.JButton();
        btSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panel2.setBackground(new java.awt.Color(153, 153, 255));

        textWorkspace.setColumns(20);
        textWorkspace.setRows(5);
        textWorkspace.setEditable(false);
        jScrollPane1.setViewportView(textWorkspace);

        textIndex.setColumns(20);
        textIndex.setRows(5);
        textIndex.setEditable(false);
        jScrollPane2.setViewportView(textIndex);

        textLocalRepository.setColumns(20);
        textLocalRepository.setRows(5);
        textLocalRepository.setEditable(false);
        jScrollPane3.setViewportView(textLocalRepository);

        textRemoteRepository.setColumns(20);
        textRemoteRepository.setRows(5);
        textRemoteRepository.setEditable(false);
        jScrollPane4.setViewportView(textRemoteRepository);

        jLabelWorkspace.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelWorkspace.setText("Workspace");

        jLabelIndex.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelIndex.setText("Index");

        jLabelLocalRepository.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLocalRepository.setText("Local Repository");

        jLabelRemoteRepository.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelRemoteRepository.setText("Remote Repository");

        jTextAreaNombreAutorYRepo.setColumns(20);
        jTextAreaNombreAutorYRepo.setRows(5);
        jTextAreaNombreAutorYRepo.setEditable(false);
        jScrollPane6.setViewportView(jTextAreaNombreAutorYRepo);

        jLabelDatosRepo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelDatosRepo.setText("Datos Del Repositorio");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabelWorkspace)
                        .addGap(182, 182, 182)
                        .addComponent(jLabelIndex)
                        .addGap(158, 158, 158)
                        .addComponent(jLabelLocalRepository)
                        .addGap(110, 110, 110)
                        .addComponent(jLabelRemoteRepository)
                        .addGap(108, 108, 108)
                        .addComponent(jLabelDatosRepo))
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWorkspace)
                    .addComponent(jLabelIndex)
                    .addComponent(jLabelLocalRepository)
                    .addComponent(jLabelRemoteRepository)
                    .addComponent(jLabelDatosRepo))
                .addGap(6, 6, 6)
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel3.setBackground(new java.awt.Color(153, 153, 255));

        jLabelNombreArchivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNombreArchivo.setText("Nombre Archivo:");

        jLabelContenidoArchivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelContenidoArchivo.setText("Contenido del Archivo:");

        textAreaContenidoArchivo.setColumns(20);
        textAreaContenidoArchivo.setRows(5);
        jScrollPane5.setViewportView(textAreaContenidoArchivo);

        btCrearArchivo.setBackground(new java.awt.Color(0, 204, 204));
        btCrearArchivo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btCrearArchivo.setText("Agregar Archivo");
        btCrearArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearArchivoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNombreArchivo)
                    .addComponent(jLabelContenidoArchivo))
                .addGap(18, 18, 18)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                    .addComponent(textFieldNombreArchivo))
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCrearArchivo)
                .addGap(72, 72, 72))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldNombreArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNombreArchivo))
                .addGap(35, 35, 35)
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContenidoArchivo)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btCrearArchivo)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panel1.setBackground(new java.awt.Color(153, 153, 255));

        btGitAdd.setBackground(new java.awt.Color(0, 204, 204));
        btGitAdd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btGitAdd.setText("Git Add");
        btGitAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGitAddActionPerformed(evt);
            }
        });

        btGitCommit.setBackground(new java.awt.Color(0, 204, 204));
        btGitCommit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btGitCommit.setText("Git Commit");
        btGitCommit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGitCommitActionPerformed(evt);
            }
        });

        btGitPush.setBackground(new java.awt.Color(0, 204, 204));
        btGitPush.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btGitPush.setText("Git Push");
        btGitPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGitPushActionPerformed(evt);
            }
        });

        btGitPull.setBackground(new java.awt.Color(0, 204, 204));
        btGitPull.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btGitPull.setText("Git Pull");
        btGitPull.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGitPullActionPerformed(evt);
            }
        });

        btGitLog.setBackground(new java.awt.Color(0, 204, 204));
        btGitLog.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btGitLog.setText("Git Log");
        btGitLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGitLogActionPerformed(evt);
            }
        });

        btSalir.setBackground(new java.awt.Color(0, 204, 204));
        btSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btSalir.setText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btGitAdd)
                    .addComponent(btGitCommit)
                    .addComponent(btGitPush)
                    .addComponent(btGitPull)
                    .addComponent(btGitLog))
                .addContainerGap(200, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSalir)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btGitAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btGitCommit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGitPush)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGitPull)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGitLog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btSalir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btGitAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGitAddActionPerformed
       VentanaGitAdd ventanitaAdd = new VentanaGitAdd(this);
       ventanitaAdd.setVisible(true);
    }//GEN-LAST:event_btGitAddActionPerformed

    private void btGitCommitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGitCommitActionPerformed
       VentanaGitCommit ventanitaCommit = new VentanaGitCommit(this);
       ventanitaCommit.setVisible(true);
    }//GEN-LAST:event_btGitCommitActionPerformed
    
    private void btCrearArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearArchivoActionPerformed
        if(this.textFieldNombreArchivo.getText().length() >= 1){
            int estado = this.repo.crearArchivo(this.textFieldNombreArchivo.getText(), this.textAreaContenidoArchivo.getText());
            if(estado == 0){
                String wsString = this.repo.workspace.toString();
                this.textWorkspace.setText(wsString);
            }
            else{
                JOptionPane.showMessageDialog(null,"EL NOMBRE DEL ARCHIVO YA EXISTE.","operación mal ingresada",JOptionPane.INFORMATION_MESSAGE);        
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"DEBE INGRESAR EL NOMBRE DEL ARCHIVO PARA AGREGARLO.","operación mal ingresada",JOptionPane.INFORMATION_MESSAGE);
        }
        this.textFieldNombreArchivo.setText("");
        this.textAreaContenidoArchivo.setText("");
    }//GEN-LAST:event_btCrearArchivoActionPerformed

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btSalirActionPerformed

    private void btGitPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGitPushActionPerformed
        this.repo.gitPush();
        this.textRemoteRepository.setText(this.repo.rRepository.toString());
    }//GEN-LAST:event_btGitPushActionPerformed

    private void btGitPullActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGitPullActionPerformed
        int estado = this.repo.gitPull();
        if(estado == 1){
            JOptionPane.showMessageDialog(null,"EL REPOSITORIO REMOTO SE ENCUENTRA VACIO.","operación mal ingresada",JOptionPane.INFORMATION_MESSAGE);        
        }
        else{
            this.textWorkspace.setText(this.repo.workspace.toString());
        }
    }//GEN-LAST:event_btGitPullActionPerformed

    private void btGitLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGitLogActionPerformed
        //String ultimos5Commit = this.repo.gotLog();
        JOptionPane.showMessageDialog(null,this.repo.gotLog(),"GIT LOG",JOptionPane.INFORMATION_MESSAGE);        
    }//GEN-LAST:event_btGitLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrearArchivo;
    private javax.swing.JButton btGitAdd;
    private javax.swing.JButton btGitCommit;
    private javax.swing.JButton btGitLog;
    private javax.swing.JButton btGitPull;
    private javax.swing.JButton btGitPush;
    private javax.swing.JButton btSalir;
    private javax.swing.JLabel jLabelContenidoArchivo;
    private javax.swing.JLabel jLabelDatosRepo;
    private javax.swing.JLabel jLabelDatosRepo1;
    private javax.swing.JLabel jLabelIndex;
    private javax.swing.JLabel jLabelIndex1;
    private javax.swing.JLabel jLabelLocalRepository;
    private javax.swing.JLabel jLabelLocalRepository1;
    private javax.swing.JLabel jLabelNombreArchivo;
    private javax.swing.JLabel jLabelRemoteRepository;
    private javax.swing.JLabel jLabelRemoteRepository1;
    private javax.swing.JLabel jLabelWorkspace;
    private javax.swing.JLabel jLabelWorkspace1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jTextAreaNombreAutorYRepo;
    private javax.swing.JTextArea jTextAreaNombreAutorYRepo1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private javax.swing.JTextArea textAreaContenidoArchivo;
    private javax.swing.JTextField textFieldNombreArchivo;
    public javax.swing.JTextArea textIndex;
    public javax.swing.JTextArea textIndex1;
    public javax.swing.JTextArea textLocalRepository;
    public javax.swing.JTextArea textLocalRepository1;
    private javax.swing.JTextArea textRemoteRepository;
    private javax.swing.JTextArea textRemoteRepository1;
    private javax.swing.JTextArea textWorkspace;
    private javax.swing.JTextArea textWorkspace1;
    // End of variables declaration//GEN-END:variables
}
